const characters = {
	old_re_lidian: ["male", "wei", 3, ["xunxun", "wangxi"], ["die_audio:lidian"]],
	ganfuren: ["female", "shu", 3, ["stdshushen", "shenzhi"]],
	std_panfeng: ["male", "qun", 4, ["stdkuangfu"]],
	caocao: ["male", "wei", 4, ["jianxiong", "hujia"], ["zhu"]],
	simayi: ["male", "wei", 3, ["fankui", "guicai"]],
	xiahoudun: ["male", "wei", 4, ["ganglie"]],
	zhangliao: ["male", "wei", 4, ["tuxi"]],
	xuzhu: ["male", "wei", 4, ["luoyi"]],
	guojia: ["male", "wei", 3, ["tiandu", "yiji"]],
	zhenji: ["female", "wei", 3, ["luoshen", "qingguo"]],
	liubei: ["male", "shu", 4, ["rende", "jijiang"], ["zhu"]],
	guanyu: ["male", "shu", 4, ["wusheng"]],
	zhangfei: ["male", "shu", 4, ["paoxiao"]],
	zhugeliang: ["male", "shu", 3, ["guanxing", "kongcheng"]],
	zhaoyun: ["male", "shu", 4, ["longdan"]],
	machao: ["male", "shu", 4, ["mashu", "tieji"]],
	huangyueying: ["female", "shu", 3, ["jizhi", "qicai"]],
	sunquan: ["male", "wu", 4, ["zhiheng", "jiuyuan"], ["zhu"]],
	ganning: ["male", "wu", 4, ["qixi"]],
	lvmeng: ["male", "wu", 4, ["keji"]],
	huanggai: ["male", "wu", 4, ["kurou"]],
	zhouyu: ["male", "wu", 3, ["yingzi", "fanjian"]],
	daqiao: ["female", "wu", 3, ["guose", "liuli"]],
	luxun: ["male", "wu", 3, ["qianxun", "lianying"]],
	sunshangxiang: ["female", "wu", 3, ["xiaoji", "jieyin"]],
	huatuo: ["male", "qun", 3, ["qingnang", "jijiu"]],
	lvbu: ["male", "qun", 4, ["wushuang"]],
	diaochan: ["female", "qun", 3, ["lijian", "biyue"]],
	huaxiong: ["male", "qun", 6, ["yaowu"]],
	gongsunzan: ["male", "qun", 4, ["reyicong"]],

	xf_yiji: ["male", "shu", 3, ["xinfu_jijie", "xinfu_jiyuan"], []],
	re_yuanshu: ["male", "qun", 4, ["rewangzun", "retongji"]],
	shenwanglang: ["male", "shen", 4, ["relieren","tianbian","decadexianzhen","xinjyzongshi","hanzhan","tianyi","olqiaoshui","regushe", "rejici","zhuandui","jianzheng","rechuhai"]],
	//天辩 陷阵 纵适 酣战 天义 乡害 鼓舌
	shenshichangshi: ["male", "shen", 3, ["juejing","scstaoluan", "scschiyan", "scszimou", "scspicai", "scsyaozhuo", "scsxiaolu", "scskuiji", "scschihe", "scsniqu", "scsanruo"]],
	shencaochong: ["male", "shen", 3, ["chengxiang","refankui", "new_reyiji", "huituo", "reganglie", "chouce", "tiandu", "new_rejianxiong", "rejieming", "refangzhu", "yuce"]],

};

export default characters;
